version: '3.3'
services:
    familybudget:
        ports:
            - '8000:8080'
        image: familybudget
        environment:
        - "ConnectionStrings__DefaultConnection=sql.data;User Id=postgres;Password=postgres;Host=localhost;Port=5432;Database=FamilyBudgetDB;"
    
    db:
        ports:
            - '5432:5432'
        image: postgres
        restart: always
        environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=FamilyBudgetDB
        volumes:
         - familybudget_data:/var/lib/postgresql/data
volumes:
  familybudget_data: